// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aoubfejqyifdefyrbjip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvdWJmZWpxeWlmZGVmeXJiamlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMzcyNTAsImV4cCI6MjA2ODYxMzI1MH0.iUe1T28-T_vT1rUzXOpWTFrv6DRAN9Zwt24ligHdCaM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});